export const gallery = {
  'Open Day':{
    '2026':[
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_1.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_2.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_3.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_4.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_5.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_6.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_7.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_8.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_9.webp',
        'caption':""
      },
       {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_10.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_11.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_12.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_13.webp',
        'caption':""
      },
       {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_14.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2026/OD_2026_15.webp',
        'caption':""
      }
    ],
    '2025':[
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_1.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_2.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_3.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_4.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_5.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_6.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_7.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_8.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_9.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_10.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_11.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_12.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_13.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_14.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_15.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_16.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_17.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2025/OD_2025_18.webp',
        'caption':""
      }
    ],
    '2024':[
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_1.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_2.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_3.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_4.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_5.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_6.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_7.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_8.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_9.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_10.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_11.webp',
        'caption':""
      }
    ]
},
'Freshers Day': {
  '2024':[
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/1.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/2.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/3.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/4.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/5.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/6.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/7.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/8.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/9.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/10.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/11.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/12.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/13.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/14.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/15.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/16.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/17.webp',
      'caption':""
    },{
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/18.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/19.webp',
      'caption':""
    },
  ],
  '2022':[
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_2.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_3.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_4.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_5.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_6.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_7.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_8.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_9.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_10.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_11.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_12.webp',
      'caption':""
    }
  ]
}
}
