export const gallery = {
  'Open Day':{
    '2024':[
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_1.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_2.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_3.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_4.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_5.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_6.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_7.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_8.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_9.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_10.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2024/OD_2024_11.webp',
        'caption':""
      },
    ],
    '2020':[
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_1.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_2.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_3.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_4.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_5.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_6.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_7.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_8.webp',
        'caption':""
      },
      {
        'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2020/OD_2020_9.webp',
        'caption':""
      }
    ],
    '2019':[
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_1.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_2.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_3.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_4.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_4.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_5.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_6.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_7.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_8.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Open_Day/OD_2019/OD_2019_9.webp',
      'caption':""
    }
  ]
},
'Freshers Day': {
  '2024':[
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/1.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/2.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/3.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/4.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/5.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/6.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/7.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/8.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/9.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/10.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/11.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/12.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/13.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/14.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/15.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/16.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/17.webp',
      'caption':""
    },{
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/18.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2024/19.webp',
      'caption':""
    },
  ],
  '2022':[
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_2.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_3.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_4.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_5.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_6.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_7.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_8.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_9.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_10.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_11.webp',
      'caption':""
    },
    {
      'imgSrc':'../../assets/images/Gallery/Freshers_Day/FD_2022/FD_2022_12.webp',
      'caption':""
    }
  ]
}
}
